In [55]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

##### 1. `import pandas as pd` and read `Dataset_Listings.csv`. Print `.shape` and `.head()`.

In [56]:
df = pd.read_csv('Eairbnb_Listings.csv')

In [57]:
df.head()

,listing_id,listing_url,name,description,latitude,longitude,property_type,room_type,accomodates,bathrooms_text,bedrooms,beds,amenities,host_id
0,50904,https://www.airbnb.com/rooms/50904,aplace/antwerp: cosy suite - fashion district,Decorated in a vintage style combined with a f...,51.218575,4.398631,Room in boutique hotel,Hotel room,2,1 private bath,1.0,1.0,"[""Kitchen"", ""Smoke alarm"", ""Hair dryer"", ""Keyp...",234077
1,116134,https://www.airbnb.com/rooms/116134,Spacious apartment nearby Mas,Enjoy your stay at our 4 person apartment in t...,51.230510,4.405930,Entire rental unit,Entire home/apt,4,2.5 baths,2.0,2.0,"[""Refrigerator"", ""Elevator"", ""Paid street park...",586942
2,218916,https://www.airbnb.com/rooms/218916,Apartment with terrace in trendy Zurenborg,Do you enjoy authentic places with a lot of ch...,51.206330,4.429420,Entire condominium (condo),Entire home/apt,5,1 bath,1.0,3.0,"[""Paid street parking off premises"", ""Kitchen""...",915664
3,224333,https://www.airbnb.com/rooms/224333,Large stylish room in 1930s house + garden,"Large bedroom in classic 1930s house. Kitchen,...",51.197720,4.458530,Private room in residential home,Private room,2,2 shared baths,1.0,1.0,"[""Fire extinguisher"", ""Backyard"", ""Long term s...",1167377
4,224682,https://www.airbnb.com/rooms/224682,APARTMENT ROSCAM - OLD CENTRE ANTWERP,"<b>The space</b><br />Apartment ""Roscam"" is a ...",51.217220,4.397900,Entire rental unit,Entire home/apt,3,1 bath,1.0,2.0,"[""Refrigerator"", ""Kitchen"", ""Smoke alarm"", ""Sh...",1263933

In [58]:
print('Shape of the dataset is', df.shape)

Shape of the dataset is (1749, 14)

##### 2. Check data types with `.dtypes`; explain what each type means.

In [59]:
df.dtypes

listing_id          int64
listing_url           str
name                  str
description           str
latitude          float64
longitude         float64
property_type         str
room_type             str
accomodates         int64
bathrooms_text        str
bedrooms          float64
beds              float64
amenities             str
host_id             int64
dtype: object

##### 3. Use `.isnull().sum()` to find missing values per column.

In [60]:
df.isnull().sum()

listing_id          0
listing_url         0
name                0
description        70
latitude            0
longitude           0
property_type       0
room_type           0
accomodates         0
bathrooms_text      0
bedrooms          128
beds               41
amenities           0
host_id             0
dtype: int64

##### 4. Select just the 'listing_id','name','host_id' and `host-id`-relevant columns using `df[[...]]`.

In [61]:
print(list(df.columns))

['listing_id', 'listing_url', 'name', 'description', 'latitude', 'longitude', 'property_type', 'room_type', 'accomodates', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'host_id']

In [62]:
df[['listing_id','name','host_id']]

      listing_id                                           name    host_id
0          50904  aplace/antwerp: cosy suite - fashion district     234077
1         116134                  Spacious apartment nearby Mas     586942
2         218916     Apartment with terrace in trendy Zurenborg     915664
3         224333     Large stylish room in 1930s house + garden    1167377
4         224682          APARTMENT ROSCAM - OLD CENTRE ANTWERP    1263933
...          ...                                            ...        ...
1744    53916524           Industrial spacious loft in Antwerp!   46300712
1745    53928545             Studio in het midden van Antwerpen   74268936
1746    53929354                Mooi appartement met open haard  334036639
1747    53949105         Kasteel Boterlaerhof vlakbij Antwerpen  377595714
1748    53983318   Infinite luxury stay in the heart of Antwerp  437309332

[1749 rows x 3 columns]

##### 5. Filter rows where `room_type == "Private room"` using boolean indexing.

In [63]:
df[df['room_type'] == 'Private room']

,listing_id,listing_url,name,description,latitude,longitude,property_type,room_type,accomodates,bathrooms_text,bedrooms,beds,amenities,host_id
3,224333,https://www.airbnb.com/rooms/224333,Large stylish room in 1930s house + garden,"Large bedroom in classic 1930s house. Kitchen,...",51.19772,4.45853,Private room in residential home,Private room,2,2 shared baths,1.0,1.0,"[""Fire extinguisher"", ""Backyard"", ""Long term s...",1167377
7,366252,https://www.airbnb.com/rooms/366252,ROOM IN FAMILY HOME near C. Station,"In the Antwerp district of Borgerhout, we live...",51.21601,4.43432,Private room in rental unit,Private room,2,Shared half-bath,1.0,1.0,"[""Elevator"", ""Fire extinguisher"", ""Long term s...",1820186
10,639013,https://www.airbnb.com/rooms/639013,The chill place in Antwerp 1,De slaapkamer bevind zich op de eerste verdiep...,51.21748,4.44560,Private room in townhouse,Private room,2,1.5 shared baths,1.0,1.0,"[""Refrigerator"", ""Fire extinguisher"", ""Backyar...",3189018
26,1172826,https://www.airbnb.com/rooms/1172826,Bedroom in large antique house near parks+trams,Large bedroom in classic 1930s Antwerp house. ...,51.19813,4.45807,Private room in residential home,Private room,3,3 shared baths,1.0,2.0,"[""Refrigerator"", ""Fire extinguisher"", ""Backyar...",1167377
28,1227242,https://www.airbnb.com/rooms/1227242,Cosy ship Hannus Antwerp Belgium,<b>The space</b><br />Hannus is a over 100 yea...,51.22775,4.40388,Private room in boat,Private room,16,2 shared baths,10.0,20.0,"[""Hot water"", ""Private entrance"", ""Fire exting...",4193029
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1718,53551895,https://www.airbnb.com/rooms/53551895,Nice condo with Antwerp skyline view,Deze centraal gelegen accommodatie is smaakvol...,51.22034,4.37984,Private room in condominium (condo),Private room,1,1 shared bath,1.0,1.0,"[""Washer"", ""Long term stays allowed"", ""First a...",73195414
1719,53553352,https://www.airbnb.com/rooms/53553352,prive kamer in Hoboken.,nieuwe kamer in Hoboken. <br />nog met de laa...,51.17775,4.35897,Private room in condominium (condo),Private room,2,1 shared bath,1.0,1.0,"[""Fire extinguisher"", ""Long term stays allowed...",311943974
1736,53825194,https://www.airbnb.com/rooms/53825194,Cozy attic room in the city center,Cosy room in the attic of an old house with a ...,51.21721,4.39359,Private room in residential home,Private room,1,1.5 shared baths,1.0,1.0,"[""Kitchen"", ""Smoke alarm"", ""Gas stove"", ""Host ...",435999398
1740,53912988,https://www.airbnb.com/rooms/53912988,the room with a charming balcony natural light,The room on the 1nd floor has a balcony overlo...,51.24336,4.43277,Private room in casa particular,Private room,2,1 shared bath,1.0,2.0,"[""Free carport on premises \u2013 2 spaces"", ""...",436739371
1743,53916361,https://www.airbnb.com/rooms/53916361,Cosy private room in a charming appartement,- Private double bed room in an apartment on t...,51.19284,4.43540,Private room in rental unit,Private room,2,1 shared bath,1.0,1.0,"[""Kitchen"", ""Smoke alarm"", ""Shampoo"", ""Hair dr...",79510923

##### 6. Use `.value_counts()` on `room_type`.

In [64]:
df.value_counts('room_type')

room_type
Entire home/apt    1379
Private room        354
Hotel room           10
Shared room           6
Name: count, dtype: int64

##### 7. Compute `.mean()`, `.median()`, `.max()` of `accomodates`.

In [65]:
print('Mean for accomodation is', df['accomodates'].mean())
print('Median for accomodation is', df['accomodates'].median())
print('Max for accomodation is', df['accomodates'].max())

Mean for accomodation is 3.7615780445969125
Median for accomodation is 3.0
Max for accomodation is 16

##### 8. Write a `for` loop that prints the first 5 listing names (practice plain Python, not just pandas).

In [66]:
print(list(df.columns))

['listing_id', 'listing_url', 'name', 'description', 'latitude', 'longitude', 'property_type', 'room_type', 'accomodates', 'bathrooms_text', 'bedrooms', 'beds', 'amenities', 'host_id']

In [67]:
for name in df['name'][:5]:
    print(name)

aplace/antwerp: cosy suite - fashion district
Spacious apartment nearby Mas
Apartment with terrace in trendy Zurenborg
Large stylish room in 1930s house + garden
APARTMENT ROSCAM - OLD CENTRE ANTWERP

In [69]:
for id in df['listing_id'][:10]:
    print(id)

50904
116134
218916
224333
224682
345959
363155
366252
522693
636664

##### 9. Create a new column `is_large = df['accomodates'] > 4`.

In [72]:
df['is_large'] = df['accomodates'] > 4

df

,listing_id,listing_url,name,description,latitude,longitude,property_type,room_type,accomodates,bathrooms_text,bedrooms,beds,amenities,host_id,is_large
0,50904,https://www.airbnb.com/rooms/50904,aplace/antwerp: cosy suite - fashion district,Decorated in a vintage style combined with a f...,51.218575,4.398631,Room in boutique hotel,Hotel room,2,1 private bath,1.0,1.0,"[""Kitchen"", ""Smoke alarm"", ""Hair dryer"", ""Keyp...",234077,False
1,116134,https://www.airbnb.com/rooms/116134,Spacious apartment nearby Mas,Enjoy your stay at our 4 person apartment in t...,51.230510,4.405930,Entire rental unit,Entire home/apt,4,2.5 baths,2.0,2.0,"[""Refrigerator"", ""Elevator"", ""Paid street park...",586942,False
2,218916,https://www.airbnb.com/rooms/218916,Apartment with terrace in trendy Zurenborg,Do you enjoy authentic places with a lot of ch...,51.206330,4.429420,Entire condominium (condo),Entire home/apt,5,1 bath,1.0,3.0,"[""Paid street parking off premises"", ""Kitchen""...",915664,True
3,224333,https://www.airbnb.com/rooms/224333,Large stylish room in 1930s house + garden,"Large bedroom in classic 1930s house. Kitchen,...",51.197720,4.458530,Private room in residential home,Private room,2,2 shared baths,1.0,1.0,"[""Fire extinguisher"", ""Backyard"", ""Long term s...",1167377,False
4,224682,https://www.airbnb.com/rooms/224682,APARTMENT ROSCAM - OLD CENTRE ANTWERP,"<b>The space</b><br />Apartment ""Roscam"" is a ...",51.217220,4.397900,Entire rental unit,Entire home/apt,3,1 bath,1.0,2.0,"[""Refrigerator"", ""Kitchen"", ""Smoke alarm"", ""Sh...",1263933,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1744,53916524,https://www.airbnb.com/rooms/53916524,Industrial spacious loft in Antwerp!,Industrial loft (110m²) with a relaxing urban ...,51.231330,4.403520,Entire loft,Entire home/apt,2,1.5 baths,1.0,1.0,"[""Refrigerator"", ""Elevator"", ""Yamaha RX-A550 s...",46300712,False
1745,53928545,https://www.airbnb.com/rooms/53928545,Studio in het midden van Antwerpen,Recent gerenoveerde rustige studio van circa 2...,51.213210,4.397080,Entire rental unit,Entire home/apt,2,1 bath,NaN,1.0,"[""Hot water"", ""Long term stays allowed"", ""Kitc...",74268936,False
1746,53929354,https://www.airbnb.com/rooms/53929354,Mooi appartement met open haard,Vanuit deze ideaal gelegen accommodatie kun je...,51.200340,4.421060,Entire rental unit,Entire home/apt,4,1 bath,1.0,2.0,"[""Kitchen"", ""Smoke alarm"", ""Outdoor furniture""...",334036639,False
1747,53949105,https://www.airbnb.com/rooms/53949105,Kasteel Boterlaerhof vlakbij Antwerpen,"Kasteel Boterlaerhof ligt ideaal gelegen, op 1...",51.212320,4.482230,Castle,Entire home/apt,16,7.5 baths,7.0,33.0,"[""Refrigerator"", ""Private garden or backyard"",...",377595714,True
1748,53983318,https://www.airbnb.com/rooms/53983318,Infinite luxury stay in the heart of Antwerp,"Experience, modern stylish luxury stay in the ...",51.214580,4.399620,Entire rental unit,Entire home/apt,3,1.5 baths,1.0,1.0,"[""Kitchen"", ""Voice command Google Bluetooth s...",437309332,False

##### 10. **Visual (Day 1):** Bar chart of listing counts per `room_type` using `matplotlib`/`seaborn`.

In [ ]:
sns.barplot = 

plt.title('Counts per room type')
plt.xlabel('Room type')
plt.ylabel('Counts per type')

plt.show()